version: "3.3"

services:
  minio.local:
    image: docker.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
    entrypoint:
      - /bin/bash
    command:
      - -c
      - |
        (sleep 5 && \
        mc alias set local http://localhost:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD && \
        mc mb local/dev-bucket && \
        mc anonymous set upload local/dev-bucket && \
        mc anonymous set download local/dev-bucket && \
        mc anonymous set public local/dev-bucket)& \
        /usr/bin/docker-entrypoint.sh minio server --console-address ":9010" /data
    environment:
      MINIO_UPDATE: "off"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Passw0rd
    ports:
      - "9000:9000"
      - "9010:9010"
    networks:
      compose_network:

networks:
  compose_network:
    ipam:
      config:
        - subnet: 172.24.24.0/24
